# Generated by Django 5.0.6 on 2024-06-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadservice', '0003_uploadedfile_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
