# Generated by Django 5.0.6 on 2024-07-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadservice', '0004_alter_uploadedfile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
